name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 21
          setup-gradle_cache-read-only: ${{ github.ref_name != 'master' && github.ref_name != 'development' }}
        
      - name: Build Erosion
        run: ./gradlew build

      - name: Archive Artifacts
        uses: GeyserMC/actions/upload-multi-artifact@master
        if: success()
        with:
          artifacts: bukkit-plugin/build/libs/Erosion.jar

      - name: Publish to Maven Repository
        if: ${{ success() && github.repository == 'GeyserMC/Erosion' }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_geysermcUsername: ${{ vars.DEPLOY_USER }}
          ORG_GRADLE_PROJECT_geysermcPassword: ${{ secrets.DEPLOY_PASS }}

      - name: Get Version
        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/Erosion' }}
        id: get-version
        run: |
          version=$(cat gradle.properties | grep -o "version=[0-9\\.]*" | cut -d"=" -f2)
          echo "VERSION=${version}" >> $GITHUB_OUTPUT

      - name: Get Release Metadata
        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/Erosion' }}
        uses: GeyserMC/actions/release@master
        id: metadata
        with:
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          files: |
            erosion:bukkit-plugin/build/libs/Erosion.jar
          releaseEnabled: false
          saveMetadata: true
          releaseProject: 'erosion'
          releaseVersion: ${{ steps.get-version.outputs.VERSION }}

      - name: Publish to Downloads API
        if: ${{ success() && github.repository == 'GeyserMC/Erosion' && github.ref_name == 'master' }}
        uses: GeyserMC/actions/upload-release@master
        with:
          username: ${{ vars.DOWNLOADS_USERNAME }}
          privateKey: ${{ secrets.DOWNLOADS_PRIVATE_KEY }}
          host: ${{ secrets.DOWNLOADS_SERVER_IP }}
          files: |
            bukkit-plugin/build/libs/Erosion.jar
          changelog: ${{ steps.metadata.outputs.body }}

      - name: Notify Discord
        if: ${{ (success() || failure()) && github.repository == 'GeyserMC/Erosion' }}
        uses: GeyserMC/actions/notify-discord@master
        with:
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          body: ${{ steps.metadata.outputs.body }}